// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2WAvQrEDFb0xzXc1xApWbvNHcgFwBE9s',
    appId: '1:780277909387:web:043fbf9fd58d2fb793d18e',
    messagingSenderId: '780277909387',
    projectId: 'doc2heal-8428c',
    authDomain: 'doc2heal-8428c.firebaseapp.com',
    storageBucket: 'doc2heal-8428c.appspot.com',
    measurementId: 'G-RS87YPD6YK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6qLMOOOhkVobmanfQgalMpjWOsv519FE',
    appId: '1:780277909387:android:27754dc139a42a9b93d18e',
    messagingSenderId: '780277909387',
    projectId: 'doc2heal-8428c',
    storageBucket: 'doc2heal-8428c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP9_8NVULKUiD18Vhl355WB4tBTpOoScE',
    appId: '1:780277909387:ios:0fcac2c6ebe4e3d493d18e',
    messagingSenderId: '780277909387',
    projectId: 'doc2heal-8428c',
    storageBucket: 'doc2heal-8428c.appspot.com',
    androidClientId: '780277909387-ug6mj3ghrm4vpv60ms8i57j7njhc4jml.apps.googleusercontent.com',
    iosClientId: '780277909387-pi4r5hfmm1huikm0ofgs6hctk4ouffjf.apps.googleusercontent.com',
    iosBundleId: 'com.example.doc2healAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP9_8NVULKUiD18Vhl355WB4tBTpOoScE',
    appId: '1:780277909387:ios:0fcac2c6ebe4e3d493d18e',
    messagingSenderId: '780277909387',
    projectId: 'doc2heal-8428c',
    storageBucket: 'doc2heal-8428c.appspot.com',
    androidClientId: '780277909387-ug6mj3ghrm4vpv60ms8i57j7njhc4jml.apps.googleusercontent.com',
    iosClientId: '780277909387-pi4r5hfmm1huikm0ofgs6hctk4ouffjf.apps.googleusercontent.com',
    iosBundleId: 'com.example.doc2healAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2WAvQrEDFb0xzXc1xApWbvNHcgFwBE9s',
    appId: '1:780277909387:web:d5713f2dbe02530593d18e',
    messagingSenderId: '780277909387',
    projectId: 'doc2heal-8428c',
    authDomain: 'doc2heal-8428c.firebaseapp.com',
    storageBucket: 'doc2heal-8428c.appspot.com',
    measurementId: 'G-FWYRYMJ806',
  );
}
